/*
 * Copyright (C) 2026  Craig Walters
 *
 * This program is free software: you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free
 *  Software Foundation, either version 3 of the License, or (at your option) any
 *  later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along with this
 *  program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *  Contact the owner via the github repository if you would like to license this software for
 *  commercial purposes outside the restrictions imposed by this copyright.
 */

package com.nozzle.export;

import com.nozzle.geometry.NozzleContour;
import com.nozzle.geometry.Point2D;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Exports a full 3-D revolved volumetric mesh from a 2-D axisymmetric nozzle
 * contour.  The contour is rotated 360° around the nozzle axis (x-axis) to
 * produce a structured hex mesh in three formats.
 *
 * <h2>Topology</h2>
 * <p>The cross-section is meshed as a polar O-grid: {@link #azimuthalCells}
 * pie-slice sectors arranged around the axis, each covering
 * {@code 360 / azimuthalCells} degrees.  Within each sector the radial
 * direction spans from the nozzle wall inward to the axis, with
 * {@link #radialCells} cells.  Cells are clustered toward the wall using
 * either a fixed {@link #expansionRatio} or a y⁺-derived grading when
 * {@link #setFirstLayerThickness(double)} is set.
 *
 * <h2>Axis cells</h2>
 * <p>The innermost face of each sector collapses to the axis line, producing
 * degenerate wedge (prism) cells at the axis.  All supported solvers handle
 * these without special treatment.  For flows where high axis accuracy is
 * critical, post-process with snappyHexMesh or use the
 * {@link CFDMeshExporter} axisymmetric wedge instead.
 *
 * <h2>Formats</h2>
 * <ul>
 *   <li>{@link Format#OPENFOAM_BLOCKMESH} — {@code blockMeshDict} with
 *       {@code axialCells × azimuthalCells} hex blocks, graded radially,
 *       and {@code inlet}, {@code outlet}, {@code wall} patches.</li>
 *   <li>{@link Format#GMSH_GEO} — {@code .geo} script that revolves the 2-D
 *       surface via {@code Extrude { Rotate { ... } { Surface; Layers;
 *       Recombine; } }} to produce a 3-D hex volume.</li>
 *   <li>{@link Format#PLOT3D} — ASCII structured grid
 *       {@code (axialCells+1) × (radialCells+1) × (azimuthalCells+1)} with
 *       power-law radial stretching and a closing azimuthal plane at
 *       {@code θ = 2π}.</li>
 * </ul>
 */
public class RevolvedMeshExporter {

    /** Creates a {@code RevolvedMeshExporter} with default settings. */
    public RevolvedMeshExporter() {}

    /** Supported 3-D revolved mesh output formats. */
    public enum Format {
        /** OpenFOAM {@code blockMeshDict} with full 360° O-grid topology. */
        OPENFOAM_BLOCKMESH,
        /**
         * Gmsh {@code .geo} script with a 3-D hex volume generated by
         * {@code Extrude { Rotate { ... } }}.
         */
        GMSH_GEO,
        /**
         * Plot3D ASCII structured grid, 3-D single block
         * {@code (ni × nj × nk)}.
         */
        PLOT3D
    }

    /** Number of cells in the axial direction (default: 100). */
    private int axialCells = 100;
    /** Number of cells in the radial direction, wall to axis (default: 50). */
    private int radialCells = 50;
    /** Number of full 360° azimuthal sectors (default: 16 = 22.5° each). */
    private int azimuthalCells = 16;
    /**
     * First cell height y₁ (metres) for y⁺-controlled radial grading.
     * When positive, overrides {@link #expansionRatio}.
     * Zero means disabled.
     */
    private double firstLayerThickness = 0.0;
    /** Fallback expansion ratio used when {@link #firstLayerThickness} is not set (default: 4.0). */
    private double expansionRatio = 4.0;

    // -------------------------------------------------------------------------
    // Fluent setters
    // -------------------------------------------------------------------------

    /**
     * Sets the number of cells in the axial direction.
     *
     * @param cells Axial cell count (&gt; 0)
     * @return This instance for method chaining
     */
    public RevolvedMeshExporter setAxialCells(int cells) {
        this.axialCells = cells;
        return this;
    }

    /**
     * Sets the number of cells in the radial direction (wall to axis).
     *
     * @param cells Radial cell count (&gt; 0)
     * @return This instance for method chaining
     */
    public RevolvedMeshExporter setRadialCells(int cells) {
        this.radialCells = cells;
        return this;
    }

    /**
     * Sets the number of azimuthal sectors that together form the full 360°
     * revolution.  Higher values increase circumferential resolution at the
     * cost of a larger mesh file.
     *
     * @param cells Azimuthal sector count (&gt; 0)
     * @return This instance for method chaining
     */
    public RevolvedMeshExporter setAzimuthalCells(int cells) {
        this.azimuthalCells = cells;
        return this;
    }

    /**
     * Sets the fallback radial expansion ratio used when
     * {@link #firstLayerThickness} is not set.
     *
     * @param ratio Expansion ratio (&ge; 1.0)
     * @return This instance for method chaining
     */
    public RevolvedMeshExporter setExpansionRatio(double ratio) {
        this.expansionRatio = ratio;
        return this;
    }

    /**
     * Sets the first cell height y₁ (metres) for y⁺-controlled radial
     * grading, overriding {@link #setExpansionRatio(double)}.
     * The grading ratio is computed as g = H / y₁, where H is the local
     * wall radius (domain height from axis to wall).
     *
     * @param t First cell height in metres (must be positive)
     * @return This instance for method chaining
     * @throws IllegalArgumentException if {@code t} is not positive
     */
    public RevolvedMeshExporter setFirstLayerThickness(double t) {
        if (t <= 0) throw new IllegalArgumentException(
                "firstLayerThickness must be positive, got: " + t);
        this.firstLayerThickness = t;
        return this;
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Exports the full 3-D revolved mesh in the requested format.
     *
     * @param contour  Nozzle contour with at least 2 generated points
     * @param filePath Destination file path
     * @param format   Target mesh format
     * @throws IOException              If the file cannot be written
     * @throws IllegalArgumentException If the contour has fewer than 2 points
     */
    public void export(NozzleContour contour, Path filePath, Format format)
            throws IOException {
        switch (format) {
            case OPENFOAM_BLOCKMESH -> exportOpenFOAM3D(contour, filePath);
            case GMSH_GEO          -> exportGmsh3D(contour, filePath);
            case PLOT3D            -> exportPlot3D3D(contour, filePath);
        }
    }

    // -------------------------------------------------------------------------
    // Grading helper
    // -------------------------------------------------------------------------

    /**
     * Returns the OpenFOAM {@code simpleGrading} ratio for the radial
     * direction.  When {@link #firstLayerThickness} is set: g = H / y₁
     * (last-to-first cell ratio; cells are smallest at the wall).
     * Falls back to {@link #expansionRatio} otherwise.
     *
     * @param domainHeight Radial distance from axis to wall (metres)
     */
    private double radialGrading(double domainHeight) {
        if (firstLayerThickness <= 0) return expansionRatio;
        return Math.max(1.0, domainHeight / firstLayerThickness);
    }

    // -------------------------------------------------------------------------
    // OpenFOAM blockMeshDict (full 3-D O-grid)
    // -------------------------------------------------------------------------

    /**
     * Exports a full 3-D OpenFOAM {@code blockMeshDict}.
     *
     * <p>The mesh consists of {@code axialCells × azimuthalCells} hex blocks
     * arranged as a polar O-grid.  Each block spans one axial step and one
     * azimuthal sector, covering the full radial extent from wall to axis.
     * Blocks at the axis are degenerate prisms (two vertices coincide on the
     * axis line); OpenFOAM's blockMesh handles these transparently.
     *
     * <p><b>Patches:</b> {@code inlet} (x = x₀), {@code outlet} (x = x_L),
     * {@code wall} (outer radial face of every block).  No axis patch is
     * needed because the axis is interior.
     *
     * @param contour  Nozzle contour with at least 2 points
     * @param filePath Destination file path
     * @throws IOException              If the file cannot be written
     * @throws IllegalArgumentException If the contour has fewer than 2 points
     */
    private void exportOpenFOAM3D(NozzleContour contour, Path filePath)
            throws IOException {
        List<Point2D> pts = contour.getContourPoints();
        if (pts.size() < 2) throw new IllegalArgumentException(
                "Contour needs at least 2 points for 3-D mesh export");

        int Ni = axialCells;
        int Nk = azimuthalCells;

        // Uniformly spaced axial stations
        double xMin = pts.getFirst().x();
        double xMax = pts.getLast().x();
        double[] xSt = new double[Ni + 1];
        double[] rSt = new double[Ni + 1];
        for (int i = 0; i <= Ni; i++) {
            xSt[i] = xMin + (double) i / Ni * (xMax - xMin);
            rSt[i] = contour.getRadiusAt(xSt[i]);
        }

        double exitRadius = pts.getLast().y();
        double g = radialGrading(exitRadius);

        // Vertex indexing:
        //   axis[i]     = i                                  (0..Ni)
        //   wall[i][k]  = (Ni+1) + i*Nk + k                 (i=0..Ni, k=0..Nk-1)
        int axisBase = 0;
        int wallBase = Ni + 1;

        try (BufferedWriter w = Files.newBufferedWriter(filePath)) {
            w.write("FoamFile\n{\n");
            w.write("    version     2.0;\n");
            w.write("    format      ASCII;\n");
            w.write("    class       dictionary;\n");
            w.write("    object      blockMeshDict;\n");
            w.write("}\n\n");
            w.write("convertToMeters 1.0;\n\n");

            // ---- Vertices ----
            w.write("vertices\n(\n");
            // Axis vertices (one per axial station)
            for (int i = 0; i <= Ni; i++) {
                w.write(String.format("    (%.8f 0.0 0.0) // axis[%d]%n",
                        xSt[i], i));
            }
            // Wall vertices (per axial station, per azimuthal sector)
            for (int i = 0; i <= Ni; i++) {
                for (int k = 0; k < Nk; k++) {
                    double theta = 2.0 * Math.PI * k / Nk;
                    double y = rSt[i] * Math.cos(theta);
                    double z = rSt[i] * Math.sin(theta);
                    w.write(String.format(
                            "    (%.8f %.8f %.8f) // wall[%d][%d]%n",
                            xSt[i], y, z, i, k));
                }
            }
            w.write(");\n\n");

            // ---- Blocks ----
            // Each block: sector k, axial step i
            //   v0 = wall[i][k],     v1 = wall[i][k+1]
            //   v2 = axis[i],        v3 = axis[i]   (degenerate)
            //   v4 = wall[i+1][k],   v5 = wall[i+1][k+1]
            //   v6 = axis[i+1],      v7 = axis[i+1] (degenerate)
            // i-direction (nx=1): azimuthal (v0→v1)
            // j-direction (ny=radialCells): radial wall→axis (v0→v3)
            // k-direction (nz=1): axial (v0→v4)
            // simpleGrading (1 g 1): g = H/y1, cells small at wall
            w.write("blocks\n(\n");
            for (int i = 0; i < Ni; i++) {
                for (int k = 0; k < Nk; k++) {
                    int kp1 = (k + 1) % Nk;
                    int v0 = wallBase + i * Nk + k;
                    int v1 = wallBase + i * Nk + kp1;
                    int v2 = axisBase + i;
                    int v3 = axisBase + i;         // degenerate
                    int v4 = wallBase + (i + 1) * Nk + k;
                    int v5 = wallBase + (i + 1) * Nk + kp1;
                    int v6 = axisBase + (i + 1);
                    int v7 = axisBase + (i + 1);   // degenerate
                    w.write(String.format(
                            "    hex (%d %d %d %d %d %d %d %d) (1 %d 1)%n",
                            v0, v1, v2, v3, v4, v5, v6, v7, radialCells));
                    w.write(String.format(
                            "    simpleGrading (1 %.4f 1)%n", g));
                }
            }
            w.write(");\n\n");

            w.write("edges\n(\n);\n\n");

            // ---- Boundary patches ----
            w.write("boundary\n(\n");

            // inlet: all sector faces at axial station i=0
            w.write("    inlet\n    {\n        type patch;\n");
            w.write("        faces\n        (\n");
            for (int k = 0; k < Nk; k++) {
                int kp1 = (k + 1) % Nk;
                // face: wall[0][k], wall[0][kp1], axis[0], axis[0]
                w.write(String.format("            (%d %d %d %d)%n",
                        wallBase + k, wallBase + kp1, axisBase, axisBase));
            }
            w.write("        );\n    }\n\n");

            // outlet: all sector faces at axial station i=Ni
            w.write("    outlet\n    {\n        type patch;\n");
            w.write("        faces\n        (\n");
            for (int k = 0; k < Nk; k++) {
                int kp1 = (k + 1) % Nk;
                w.write(String.format("            (%d %d %d %d)%n",
                        wallBase + Ni * Nk + k,
                        wallBase + Ni * Nk + kp1,
                        axisBase + Ni,
                        axisBase + Ni));
            }
            w.write("        );\n    }\n\n");

            // wall: outer radial face of each block (the nozzle surface)
            w.write("    wall\n    {\n        type wall;\n");
            w.write("        faces\n        (\n");
            for (int i = 0; i < Ni; i++) {
                for (int k = 0; k < Nk; k++) {
                    int kp1 = (k + 1) % Nk;
                    // quad: wall[i][k] → wall[i+1][k] → wall[i+1][kp1] → wall[i][kp1]
                    w.write(String.format("            (%d %d %d %d)%n",
                            wallBase + i * Nk + k,
                            wallBase + (i + 1) * Nk + k,
                            wallBase + (i + 1) * Nk + kp1,
                            wallBase + i * Nk + kp1));
                }
            }
            w.write("        );\n    }\n");

            w.write(");\n\n");
            w.write("mergePatchPairs\n(\n);\n");
        }
    }

    // -------------------------------------------------------------------------
    // Gmsh .geo (2-D profile + Extrude Rotate)
    // -------------------------------------------------------------------------

    /**
     * Exports a Gmsh {@code .geo} script that revolves the 2-D nozzle surface
     * into a full 3-D hex volume using {@code Extrude { Rotate { ... } }}.
     *
     * <p>The 2-D profile is defined in the x-y plane (y = radial direction).
     * The rotation axis is the x-axis (nozzle centreline).  A full 2π
     * revolution is performed in {@link #azimuthalCells} layers with hex
     * recombination enabled.
     *
     * <p><b>Physical groups generated:</b>
     * <ul>
     *   <li>{@code "fluid"} — the extruded volume.</li>
     *   <li>{@code "inlet"}, {@code "outlet"}, {@code "wall"} — lateral
     *       surfaces derived from the boundary curves; exact surface tags are
     *       printed as comments for manual verification.</li>
     * </ul>
     *
     * @param contour  Nozzle contour with at least 2 points
     * @param filePath Destination {@code .geo} file path
     * @throws IOException              If the file cannot be written
     * @throws IllegalArgumentException If the contour has fewer than 2 points
     */
    private void exportGmsh3D(NozzleContour contour, Path filePath)
            throws IOException {
        List<Point2D> pts = contour.getContourPoints();
        if (pts.size() < 2) throw new IllegalArgumentException(
                "Contour needs at least 2 points for 3-D mesh export");

        try (BufferedWriter w = Files.newBufferedWriter(filePath)) {
            w.write("// Gmsh .geo — full 3-D revolved nozzle mesh\n");
            w.write("// Generated by Nozzle MOC Design Tool\n");
            w.write("// Rotation axis: x-axis (nozzle centreline)\n\n");

            double lc = pts.getLast().y() / radialCells;
            w.write(String.format("lc = %.6f; // characteristic length%n%n", lc));

            // ---- 2-D profile points ----
            // Wall points (in x-y plane, y = radial direction)
            int pid = 1;
            int wallFirst = pid;
            for (Point2D p : pts) {
                w.write(String.format("Point(%d) = {%.8f, %.8f, 0, lc};%n",
                        pid++, p.x(), p.y()));
            }
            int wallLast = pid - 1;

            // Axis points at inlet and outlet
            int axisInlet  = pid;
            w.write(String.format("Point(%d) = {%.8f, 0, 0, lc}; // axis inlet%n",
                    pid++, pts.getFirst().x()));
            int axisOutlet = pid;
            w.write(String.format("Point(%d) = {%.8f, 0, 0, lc}; // axis outlet%n",
                    pid++, pts.getLast().x()));
            w.write("\n");

            // ---- Curves ----
            int lid = 1;

            // Wall spline
            StringBuilder wallPts = new StringBuilder();
            for (int i = wallFirst; i <= wallLast; i++) {
                if (i > wallFirst) wallPts.append(", ");
                wallPts.append(i);
            }
            w.write(String.format("Spline(%d) = {%s}; // wall%n", lid, wallPts));
            int wallCurve   = lid++;

            // Outlet line: wall exit → axis outlet
            w.write(String.format("Line(%d) = {%d, %d}; // outlet%n",
                    lid, wallLast, axisOutlet));
            int outletCurve = lid++;

            // Axis line: axis outlet → axis inlet
            w.write(String.format("Line(%d) = {%d, %d}; // axis%n",
                    lid, axisOutlet, axisInlet));
            int axisCurve   = lid++;

            // Inlet line: axis inlet → wall inlet
            w.write(String.format("Line(%d) = {%d, %d}; // inlet%n",
                    lid, axisInlet, wallFirst));
            int inletCurve  = lid++;
            w.write("\n");

            // ---- 2-D surface ----
            // CurveLoop orientation: wall → outlet → axis (reversed) → inlet (reversed)
            w.write(String.format(
                    "Curve Loop(1) = {%d, %d, %d, %d};%n",
                    wallCurve, outletCurve, axisCurve, inletCurve));
            w.write("Plane Surface(1) = {1};\n\n");

            // Transfinite directives for the 2-D surface (used by Extrude Recombine)
            w.write(String.format(
                    "Transfinite Curve {%d, %d} = %d Using Progression 1;%n",
                    axisCurve, wallCurve, axialCells + 1));
            w.write(String.format(
                    "Transfinite Curve {%d, %d} = %d Using Progression 1;%n",
                    inletCurve, outletCurve, radialCells + 1));
            w.write("Transfinite Surface {1};\n");
            w.write("Recombine Surface {1};\n\n");

            // ---- 3-D revolution ----
            w.write("// Revolve the 2-D surface 360° around the x-axis\n");
            w.write(String.format(
                    "out[] = Extrude { Rotate { {1,0,0}, {0,0,0}, 2*Pi } {%n" +
                    "    Surface{1}; Layers{%d}; Recombine;%n" +
                    "} };%n%n",
                    azimuthalCells));

            // ---- Physical groups ----
            // out[0] = "top" face (coincides with original surface for full rotation)
            // out[1] = volume
            // out[2..wallCurve+1] = lateral surface from wallCurve
            // out[2..outletCurve+1] = lateral surface from outletCurve
            // etc.  Exact indices depend on CurveLoop ordering; listed as comments.
            w.write("Physical Volume(\"fluid\") = {out[1]};\n\n");
            w.write("// Lateral surface tag hints (verify with Gmsh GUI if needed):\n");
            w.write(String.format(
                    "// wall   surface generated from wall   curve %d → out[%d]%n",
                    wallCurve,   wallCurve   + 1));
            w.write(String.format(
                    "// outlet surface generated from outlet curve %d → out[%d]%n",
                    outletCurve, outletCurve + 1));
            w.write(String.format(
                    "// inlet  surface generated from inlet  curve %d → out[%d]%n",
                    inletCurve,  inletCurve  + 1));
            w.write(String.format(
                    "Physical Surface(\"wall\")   = {out[%d]};%n",   wallCurve   + 1));
            w.write(String.format(
                    "Physical Surface(\"outlet\") = {out[%d]};%n",   outletCurve + 1));
            w.write(String.format(
                    "Physical Surface(\"inlet\")  = {out[%d]};%n",   inletCurve  + 1));
        }
    }

    // -------------------------------------------------------------------------
    // Plot3D 3-D structured grid
    // -------------------------------------------------------------------------

    /**
     * Exports a 3-D structured grid in ASCII Plot3D format, single block.
     *
     * <p>Grid dimensions: {@code (axialCells+1) × (radialCells+1) ×
     * (azimuthalCells+1)}.  The extra azimuthal plane at index
     * {@code k = azimuthalCells} closes the ring by repeating {@code k = 0}.
     *
     * <p>Radial spacing uses a power-law stretch:
     * {@code η'(j) = 1 − (1 − j/N_j)^p} where {@code p} is derived from
     * {@link #firstLayerThickness} (when set) or {@link #expansionRatio}
     * otherwise.
     *
     * @param contour  Nozzle contour used to evaluate the wall radius at each
     *                 axial station
     * @param filePath Destination file path
     * @throws IOException              If the file cannot be written
     * @throws IllegalArgumentException If the contour has fewer than 2 points
     */
    private void exportPlot3D3D(NozzleContour contour, Path filePath)
            throws IOException {
        List<Point2D> pts = contour.getContourPoints();
        if (pts.size() < 2) throw new IllegalArgumentException(
                "Contour needs at least 2 points for 3-D mesh export");

        int ni = axialCells + 1;
        int nj = radialCells + 1;
        int nk = azimuthalCells + 1;  // closing plane at k=nk-1 repeats k=0

        double xMin      = pts.getFirst().x();
        double xMax      = pts.getLast().x();
        double exitRadius = pts.getLast().y();

        // Power-law radial exponent (wall-clustering: η→1 at wall, η=0 at axis)
        double p = computePlot3dExponent(exitRadius);

        // Build coordinate arrays
        double[] xStation = new double[ni];
        double[] rWall    = new double[ni];
        for (int i = 0; i < ni; i++) {
            xStation[i] = xMin + (double) i / (ni - 1) * (xMax - xMin);
            rWall[i]    = contour.getRadiusAt(xStation[i]);
        }

        try (BufferedWriter w = Files.newBufferedWriter(filePath)) {
            w.write("1\n");  // single block
            w.write(String.format("%d %d %d%n", ni, nj, nk));

            // X-coordinates  (k outer, j middle, i inner)
            int col = 0;
            for (int k = 0; k < nk; k++) {
                for (int j = 0; j < nj; j++) {
                    for (int i = 0; i < ni; i++) {
                        w.write(String.format("%.8e ", xStation[i]));
                        if (++col % 5 == 0) w.write("\n");
                    }
                }
            }
            w.write("\n");

            // Y-coordinates  y = r(i,j) * cos(θ_k)
            col = 0;
            for (int k = 0; k < nk; k++) {
                double theta = 2.0 * Math.PI * k / (nk - 1);
                double cosT  = Math.cos(theta);
                for (int j = 0; j < nj; j++) {
                    double eta = 1.0 - Math.pow(1.0 - (double) j / (nj - 1), p);
                    for (int i = 0; i < ni; i++) {
                        w.write(String.format("%.8e ", eta * rWall[i] * cosT));
                        if (++col % 5 == 0) w.write("\n");
                    }
                }
            }
            w.write("\n");

            // Z-coordinates  z = r(i,j) * sin(θ_k)
            col = 0;
            for (int k = 0; k < nk; k++) {
                double theta = 2.0 * Math.PI * k / (nk - 1);
                double sinT  = Math.sin(theta);
                for (int j = 0; j < nj; j++) {
                    double eta = 1.0 - Math.pow(1.0 - (double) j / (nj - 1), p);
                    for (int i = 0; i < ni; i++) {
                        w.write(String.format("%.8e ", eta * rWall[i] * sinT));
                        if (++col % 5 == 0) w.write("\n");
                    }
                }
            }
        }
    }

    /**
     * Returns the Plot3D power-law stretching exponent p.
     * With {@link #firstLayerThickness} set: p = ln(H/y₁) / ln(N_j).
     * Falls back to {@link #expansionRatio} otherwise.
     */
    private double computePlot3dExponent(double domainHeight) {
        if (firstLayerThickness <= 0) return expansionRatio;
        double ratio = Math.max(1.0, domainHeight / firstLayerThickness);
        return Math.log(ratio) / Math.log(radialCells);
    }
}
